version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-reactive-processor
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
#      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  db:
    image: killbill/mariadb:0.20
    volumes:
      - /Users/uengine/docker/killbill:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
#  counter-service:
#    depends_on:
#      - eureka
#      - kafka
#      - mongo
#      - redis
#    build: ./counter-service/
#    ports:
#      - "9010"
#    restart: always
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_HOST: eureka
#      KAFKA_HOST: kafka
#      MONGO_HOST: mongo
#      REDIS_HOST: redis

volumes:
  data-volume: