api-info:
  title: UENGINE METER API DOCUMENT
  description: UENGINE METER API DOCUMENT for Cloud service
  terms-of-service-url: https://seungpilpark.github.io/uEngineMeter/#/
  contact: UENGINE
  license: MIT
  license-url:
  version: 1

spring:
  application:
      name: meter-service
  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

---
spring:
  profiles: local
  data:
    rest:
      base-path: meter
  cloud:
    stream:
      kafka:
        binder:
          #brokers: 52.79.164.208:9092
          brokers: 127.0.0.1:9092
      bindings:
        kb-consumer:
          group: meter-service
          destination: kb
        kb-producer:
          destination: kb
        limit-consumer:
          group: meter-service
          destination: meter-limit
        limit-producer:
          destination: meter-limit
        record-consumer:
          group: meter-service
          destination: meter-record
        record-producer:
          destination: meter-record


  redis: 127.0.0.1:6379
  #redis-host: redis.pas-mini.io:6379
  influxdb:
    url: http://localhost:8086
    username: admin
    password: password
    database: meter
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/killbill
    username: root
    password: killbill

killbill:
  url: http://localhost:9090
  username: admin
  password: password
  apikey: admin
  apisecret: password

